services:
  app:
    build:
      args:
        user: ${USER}
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - prex_network
    depends_on:
      - nginx
      - db
    ports:
      - "9000:9000"

  db:
    image: 'mysql/mysql-server:8.0.32'
    restart: unless-stopped
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: 'prex_password'
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: 'prex_giphy'
      MYSQL_USER: 'prex'
      MYSQL_PASSWORD: 'prex_password'
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - 'mysql-serve:/var/lib/mysql'
    networks:
      - prex_network

  nginx:
    image: nginx:1.20-alpine
    restart: unless-stopped
    ports:
        - target: 80
          published: 80
          mode: host
          host_ip: 0.0.0.0
    volumes:
      - ./:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - prex_network

networks:
  prex_network:
    driver: bridge

volumes:
  mysql-serve:
    driver: local
